name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: portfolio-manager-433711

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/portfolio-manager-433711/gcr.io/portfolio-manager-app:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-docker.pkg.dev/portfolio-manager-433711/gcr.io/portfolio-manager-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio-manager-app \
            --image us-docker.pkg.dev/portfolio-manager-433711/gcr.io/portfolio-manager-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
